/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.calculator;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().add(args[1]));
    }

    public double add(String numbers) {
        return 0;
    }
}
