/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAddMethod() {
        App sut = new App();
        assertNotNull(sut.add(""));
    }

    @Test
    public void fails() {
        fail("This Test Just Fails");
    }
}
